name: Test and build dev

on:
  push:
    branches:
      - dev
      - master
    tags:
      - 'v*'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        runtime: [ "win-x64", "win-x86", "linux-x64", "osx-x64" ]

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: dotnet publish -r ${{ matrix.runtime }} -c Release /p:PublishSingleFile=true -o ./output/
      working-directory: ./Frontend/
    - name: Zip artifacts
      run: zip --junk-paths -r ./artifact.zip ./Frontend/output/
    - uses: actions/upload-artifact@v1
      with:
        name: SM3-${{ matrix.runtime }}.zip
        path: ./artifact.zip

  test:
    name: docker-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build Docker Image
        run: docker build --target test -t test:latest -f ./Frontend/Dockerfile .
      - name: Run Tests
        run: docker run test:latest

  docker-build:
    name: docker-build
    runs-on: ubuntu-latest
    needs: [ test ]

    steps:
      - uses: actions/checkout@v1
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: SharpenedMinecraft/SM3
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          dockerfile: ./Frontend/Dockerfile