name: Test and build

on:
  push:
    branches:
      - dev
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        runtime: [ "win-x64", "win-x86", "linux-x64", "osx-x64" ]

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: dotnet publish -r ${{ matrix.runtime }} -c Release /p:PublishSingleFile=true -o ./output/
      working-directory: ./Frontend/
    - name: Zip artifacts
      run: zip --junk-paths -r ./artifact.zip ./Frontend/output/
    - uses: actions/upload-artifact@v1
      with:
        name: SM3-${{ matrix.runtime }}.zip
        path: ./artifact.zip

  test:
    name: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Test with dotnet
      run: dotnet test
      working-directory: ./Frontend.Tests/
