name: Test on PR

on: pull_request

jobs:
  test:
    name: docker-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build Docker Image
        run: docker build --target test -t test:latest -f ./Frontend/Dockerfile .
      - name: Run Tests
        run: docker run test:latest
